### ISSUE TITLE
Erigon stuck at [6/15 Execution] Blocks execution

### ISSUE THREAD

**Issue by atdefinative** [allada/bsc-archive-snapshot#29]
After snapshot download, on first run of Erigon, it gets stuck in execution stage.
No execution stage status messages
Tried using `Im4gn.4xlarge` and `i3en.3xlarge` (Both using zfs as recommended in the script)
Ctrl+C does not exit Erigon. Instead, need to press several times for panic.
Output:
```
root@ip-172-31-63-1:/home/ubuntu# erigon --chain=bsc --datadir=/media/datadir/datadir --metrics --metrics.addr=0.0.0.0 --metrics.port=6060 --private.api.addr=0.0.0.0:9090 --http.api=eth,erigon,web3,net,debug,trace,txpool --ws --pprof --p
prof.addr=0.0.0.0 --pprof.port=6061 --snapshots=true --db.pagesize=16k
INFO[09-05|07:33:11.513] Starting metrics server                  addr=http://0.0.0.0:6060/debug/metrics/prometheus
INFO[09-05|07:33:11.513] Starting pprof server                    cpu="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/profile?seconds=20" heap="go tool pprof -lines -http=: http://0.0.0.0:6061/debug/pprof/heap"
INFO[09-05|07:33:11.513] Build info                               git_branch=alpha git_tag=v2021.10.03-1804-g4067b7c4d git_commit=4067b7c4da6c5d741d3027d95ae2afdf6b7a943a
INFO[09-05|07:33:11.513] Starting Erigon on BSC mainnet...
INFO[09-05|07:33:11.517] Maximum peer count                       ETH=100 total=100
INFO[09-05|07:33:11.517] starting HTTP APIs                       APIs=eth,erigon,web3,net,debug,trace,txpool
INFO[09-05|07:33:11.517] torrent verbosity                        level=WRN
INFO[09-05|07:33:13.618] Set global gas cap                       cap=50000000
INFO[09-05|07:33:13.623] Opening Database                         label=chaindata path=/media/datadir/datadir/chaindata
INFO[09-05|07:33:13.636] Initialised chain configuration          config="{ChainID: 56 Ramanujan: 0, Niels: 0, MirrorSync: 5184000, Bruno: 13082000, Euler: 18907621, Engine: parlia}" genesis=0x0d21840abff46b96c84b2ac9e10e4f5cdaeb5693cb66
5db62a2f3b02d2d57b5b
INFO[09-05|07:33:13.636] Effective                                prune_flags= snapshot_flags="--snapshots=true" history.v2=false
INFO[09-05|07:33:15.183] Initialising Ethereum protocol           network=56
INFO[09-05|07:33:17.026] Starting private RPC server              on=0.0.0.0:9090
INFO[09-05|07:33:17.026] new subscription to logs established
INFO[09-05|07:33:17.026] rpc filters: subscribing to Erigon events
INFO[09-05|07:33:17.026] New txs subscriber joined
INFO[09-05|07:33:17.026] new subscription to newHeaders established
INFO[09-05|07:33:17.027] Reading JWT secret                       path=/media/datadir/datadir/jwt.hex
INFO[09-05|07:33:17.027] Generated JWT secret                     path=/media/datadir/datadir/jwt.hex
INFO[09-05|07:33:17.027] HTTP endpoint opened for Engine API      url=localhost:8551 ws=true ws.compression=true
INFO[09-05|07:33:17.027] HTTP endpoint opened                     url=localhost:8545 ws=true ws.compression=true grpc=false
INFO[09-05|07:33:17.031] Started P2P networking                   version=66 self=enode://a78881ed161becdbbec3ab464b3f2e285f59af5460505ddbaa268e1436240ddf2bee6189f69c97e08e3fd07c0fa5b96be599dafaf9edf8d82a7e377aa7a42257@127.0.0.1:30303 na
me=erigon/v2022.09.1-alpha-4067b7c4/linux-amd64/go1.18.1
INFO[09-05|07:33:17.036] [txpool] Started
INFO[09-05|07:33:17.062] [Snapshots] Fetching torrent files metadata
INFO[09-05|07:33:23.426] [Snapshots] Stat                         blocks=20932k indices=20932k alloc=2.8GB sys=3.0GB
INFO[09-05|07:33:23.426] [1/15 Headers] Waiting for headers...    from=21050202
INFO[09-05|07:33:40.936] [1/15 Headers] Processed                 highest inserted=21060662 age=2s
INFO[09-05|07:33:47.085] [4/15 Bodies] Processing bodies...       from=21050202 to=21060662
INFO[09-05|07:34:07.086] [4/15 Bodies] Wrote block bodies         block_num=21051089 delivery/sec=11.8MB wasted/sec=2.6MB alloc=4.2GB sys=4.7GB
INFO[09-05|07:34:17.027] [txpool] stat                            block=21050202 pending=29 baseFee=0 queued=79 alloc=4.2GB sys=4.7GB
INFO[09-05|07:34:35.115] [4/15 Bodies] Processed                  highest=21060662
INFO[09-05|07:34:35.115] [5/15 Senders] Started                   from=21050202 to=21060662
INFO[09-05|07:34:51.752] [6/15 Execution] Blocks execution        from=21050202 to=21060662
INFO[09-05|07:35:15.183] [p2p] GoodPeers                          eth66=18
INFO[09-05|07:35:17.027] [txpool] stat                            block=21050202 pending=29 baseFee=0 queued=79 alloc=5.3GB sys=6.9GB
INFO[09-05|07:36:17.027] [txpool] stat                            block=21050202 pending=30 baseFee=0 queued=90 alloc=11.9GB sys=13.1GB
INFO[09-05|07:37:15.184] [p2p] GoodPeers                          eth66=28
INFO[09-05|07:37:17.028] [txpool] stat                            block=21050202 pending=32 baseFee=0 queued=92 alloc=19.7GB sys=21.7GB
INFO[09-05|07:38:17.054] [txpool] stat                            block=21050202 pending=1659 baseFee=0 queued=2325 alloc=22.8GB sys=25.2GB
INFO[09-05|07:39:15.183] [p2p] GoodPeers                          eth66=29
INFO[09-05|07:39:17.031] [txpool] stat                            block=21050202 pending=2228 baseFee=0 queued=3302 alloc=33.0GB sys=36.5GB
INFO[09-05|07:40:17.030] [txpool] stat                            block=21050202 pending=3078 baseFee=0 queued=4549 alloc=33.4GB sys=41.4GB
INFO[09-05|07:41:15.183] [p2p] GoodPeers                          eth66=26
INFO[09-05|07:41:17.030] [txpool] stat                            block=21050202 pending=3892 baseFee=0 queued=5642 alloc=36.5GB sys=41.4GB
INFO[09-05|07:42:17.028] [txpool] stat                            block=21050202 pending=4547 baseFee=0 queued=6812 alloc=21.6GB sys=41.4GB
^CINFO[09-05|07:42:26.445] Got interrupt, shutting down...
INFO[09-05|07:42:26.449] Exiting Engine...
INFO[09-05|07:42:26.449] Exiting...
INFO[09-05|07:42:26.452] RPC server shutting down
INFO[09-05|07:42:26.452] RPC server shutting down
INFO[09-05|07:42:26.454] RPC server shutting down
WARN[09-05|07:42:26.457] Failed to serve http endpoint            err="http: Server closed"
INFO[09-05|07:42:26.457] Engine HTTP endpoint close               url=localhost:8551
WARN[09-05|07:42:26.457] Failed to serve http endpoint            err="http: Server closed"
INFO[09-05|07:42:26.458] HTTP endpoint closed                     url=localhost:8545
^CWARN[09-05|07:42:33.308] Already shutting down, interrupt more to panic. times=9
^CWARN[09-05|07:43:04.647] Already shutting down, interrupt more to panic. times=8
^CWARN[09-05|07:43:05.480] Already shutting down, interrupt more to panic. times=7
^CWARN[09-05|07:43:05.671] Already shutting down, interrupt more to panic. times=6
^CWARN[09-05|07:43:05.847] Already shutting down, interrupt more to panic. times=5
^CWARN[09-05|07:43:06.023] Already shutting down, interrupt more to panic. times=4
^CWARN[09-05|07:43:06.247] Already shutting down, interrupt more to panic. times=3
^CWARN[09-05|07:43:06.647] Already shutting down, interrupt more to panic. times=2
^CWARN[09-05|07:43:06.983] Already shutting down, interrupt more to panic. times=1
^Cpanic: boom

goroutine 5445 [running]:
github.com/ledgerwatch/erigon/internal/debug.LoudPanic(...)
        github.com/ledgerwatch/erigon/internal/debug/loudpanic.go:26
github.com/ledgerwatch/erigon/internal/debug.ListenSignals({0x1fedc40?, 0xc000a4eb00})
        github.com/ledgerwatch/erigon/internal/debug/signal.go:38 +0x359
created by github.com/ledgerwatch/erigon/cmd/utils.StartNode
        github.com/ledgerwatch/erigon/cmd/utils/cmd.go:58 +0xaa

goroutine 1 [chan receive, 9 minutes]:
github.com/ledgerwatch/erigon/node.(*Node).Wait(...)
        github.com/ledgerwatch/erigon/node/node.go:265
github.com/ledgerwatch/erigon/turbo/node.(*ErigonNode).Serve(0xc015324880)
        github.com/ledgerwatch/erigon/turbo/node/node.go:32 +0x7c
main.runErigon(0xc000543b80?)
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:64 +0x325
github.com/urfave/cli.HandleAction({0x16b1980?, 0x1de1738?}, 0xc00027f340?)
        github.com/urfave/cli@v1.22.9/app.go:526 +0x50
github.com/urfave/cli.(*App).Run(0xc00027f340, {0xc000132000, 0xe, 0xe})
        github.com/urfave/cli@v1.22.9/app.go:286 +0x7c5
main.main()
        github.com/ledgerwatch/erigon/cmd/erigon/main.go:35 +0x75

goroutine 19 [sleep, 3 minutes]:
time.Sleep(0x22ecb25c00)
        runtime/time.go:194 +0x12e
github.com/VictoriaMetrics/metrics.summariesSwapCron(0x45d964b800)
        github.com/VictoriaMetrics/metrics@v1.22.2/summary.go:237 +0x36
created by github.com/VictoriaMetrics/metrics.registerSummaryLocked
        github.com/VictoriaMetrics/metrics@v1.22.2/summary.go:211 +0x125

goroutine 8 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f00886b84c8, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0000d0000?, 0x0?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc0000d0000)
        internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc0000d0000)
        net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc0002a0030)
        net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc0002a0030)
        net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc0001320e0, {0x1ffcbc0, 0xc0002a0030})
        net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc0001320e0)
        net/http/server.go:2968 +0x7d
net/http.ListenAndServe(...)
        net/http/server.go:3222
github.com/ledgerwatch/erigon/metrics/exp.Setup.func2()
        github.com/ledgerwatch/erigon/metrics/exp/exp.go:26 +0x69
created by github.com/ledgerwatch/erigon/metrics/exp.Setup
        github.com/ledgerwatch/erigon/metrics/exp/exp.go:25 +0x145

goroutine 9 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f00886b83d8, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0004a4000?, 0x0?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc0004a4000)
        internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc0004a4000)
        net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000448018)
        net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc000448018)
        net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc00049e000, {0x1ffcbc0, 0xc000448018})
        net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc00049e000)
        net/http/server.go:2968 +0x7d
net/http.ListenAndServe(...)
        net/http/server.go:3222
github.com/ledgerwatch/erigon/internal/debug.StartPProf.func2()
        github.com/ledgerwatch/erigon/internal/debug/flags.go:252 +0x69
created by github.com/ledgerwatch/erigon/internal/debug.StartPProf
        github.com/ledgerwatch/erigon/internal/debug/flags.go:251 +0x258

goroutine 5259 [chan receive, 9 minutes]:
github.com/ledgerwatch/erigon-lib/direct.(*SubscribeLogsStreamC).Recv(0xc0000d1048?)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:181 +0x2b
github.com/ledgerwatch/erigon/cmd/rpcdaemon/rpcservices.(*RemoteBackend).SubscribeLogs(0xc00d0c5130, {0x1ffea88, 0xc000a4af40}, 0xc00900c000, 0x0?)
        github.com/ledgerwatch/erigon/cmd/rpcdaemon/rpcservices/eth_backend.go:156 +0x222
github.com/ledgerwatch/erigon/turbo/rpchelper.New.func2()
        github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:108 +0xec
created by github.com/ledgerwatch/erigon/turbo/rpchelper.New
        github.com/ledgerwatch/erigon/turbo/rpchelper/filters.go:98 +0x3d9

goroutine 4049 [sleep]:
time.Sleep(0x6fc23ac00)
        runtime/time.go:194 +0x12e
github.com/ledgerwatch/erigon/cmd/downloader/downloader.MainLoop.func1()
        github.com/ledgerwatch/erigon/cmd/downloader/downloader/downloader.go:355 +0x4d
created by github.com/ledgerwatch/erigon/cmd/downloader/downloader.MainLoop
        github.com/ledgerwatch/erigon/cmd/downloader/downloader/downloader.go:333 +0x11e

goroutine 4995 [chan receive, 9 minutes]:
github.com/ledgerwatch/erigon-lib/direct.(*SubscribeLogsStreamS).Recv(0xc00d0c4730?)
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:154 +0x2b
github.com/ledgerwatch/erigon/ethdb/privateapi.(*LogsFilterAggregator).subscribeLogs(0xc00d0c4730, {0x2008990, 0xc006ae2000})
        github.com/ledgerwatch/erigon/ethdb/privateapi/logsfilter.go:131 +0xbc
github.com/ledgerwatch/erigon/ethdb/privateapi.(*EthBackendServer).SubscribeLogs(0xd061ab?, {0x2008990?, 0xc006ae2000?})
        github.com/ledgerwatch/erigon/ethdb/privateapi/ethbackend.go:677 +0x2c
github.com/ledgerwatch/erigon-lib/direct.(*EthBackendClientDirect).SubscribeLogs.func1()
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:121 +0x9b
created by github.com/ledgerwatch/erigon-lib/direct.(*EthBackendClientDirect).SubscribeLogs
        github.com/ledgerwatch/erigon-lib@v0.0.0-20220902083702-215695f9392d/direct/eth_backend_client.go:118 +0x15b

goroutine 5270 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7f007980dcb0, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc0000d1080?, 0xc0001260f0?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc0000d1080)
        internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc0000d1080)
        net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc015b10228)
        net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc015b10228)
        net/tcpsock.go:288 +0x3d
github.com/ledgerwatch/erigon/p2p.(*Server).listenLoop(0xc00a8402c0, {0x1ffea88, 0xc00cb8ed00})
        github.com/ledgerwatch/erigon/p2p/server.go:892 +0x753
github.com/ledgerwatch/erigon/p2p.(*Server).setupListening.func2()
        github.com/ledgerwatch/erigon/p2p/server.go:721 +0x74
created by github.com/ledgerwatch/erigon/p2p.(*Server).setupListening
        github.com/ledgerwatch/erigon/p2p/server.go:718 +0x26d

goroutine 5444 [runnable, locked to thread]:
github.com/ledgerwatch/secp256k1._Cfunc_secp256k1_ext_ecdsa_recover(0x7f008858c010, 0xc5cfbda0a0, 0xc50e733fa0, 0xc5cfbcb5c0)
        _cgo_gotypes.go:250 +0x4c
github.com/ledgerwatch/secp256k1.RecoverPubkeyWithContext.func1(0x20?, {0xc5cfbda0a0, 0x16b9fc0?, 0x0?}, {0x0?, 0x0, 0xc5cfbd1880?}, 0xc5cfbcb6a0?, 0x20?)
        github.com/ledgerwatch/secp256k1@v1.0.0/secp256.go:171 +0x8a
github.com/ledgerwatch/secp256k1.RecoverPubkeyWithContext(0xc5cfbd16c0?, {0xc5cfbcb5c0?, 0x0?, 0x20?}, {0xc50e733fa0?, 0x41?, 0xc0002c5000?}, {0x0, 0x0, 0x0})
        github.com/ledgerwatch/secp256k1@v1.0.0/secp256.go:171 +0x14e
github.com/ledgerwatch/secp256k1.RecoverPubkey(...)
        github.com/ledgerwatch/secp256k1@v1.0.0/secp256.go:147
github.com/ledgerwatch/erigon/crypto.Ecrecover({0xc5cfbcb5c0?, 0x34c7f531a443290a?, 0x15a6793946363c01?}, {0xc50e733fa0?, 0x18b9c60?, 0xc50e765680?})
        github.com/ledgerwatch/erigon/crypto/signature_cgo.go:32 +0x4d
github.com/ledgerwatch/erigon/consensus/parlia.ecrecover(0xc50e765680, 0x0?, 0x0?)
        github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:163 +0x245
github.com/ledgerwatch/erigon/consensus/parlia.(*Snapshot).apply(0xc662ba19f0, {0xc5b7a00000, 0x141335a, 0xc00011a8a0?}, {0x2004fb8, 0xc0fa2d2c30}, {0x0, 0x0, 0x0}, 0xc0002c5000)
        github.com/ledgerwatch/erigon/consensus/parlia/snapshot.go:196 +0x76f
github.com/ledgerwatch/erigon/consensus/parlia.(*Parlia).snapshot(0xc00d202a00, {0x2004fb8, 0xc0fa2d2c30}, 0x49f7d62eb8e81f8f?, {0xd, 0x21, 0x84, 0xa, 0xbf, 0xf4, ...}, ...)
        github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:565 +0x8c5
github.com/ledgerwatch/erigon/consensus/parlia.(*Parlia).finalize(0xc00d202a00, 0xc000243900, 0x0?, {0xc0e5db1500?, 0xc0e7994618?, 0x432367?}, {0xc09352ea00?, 0x35, 0x40}, {0x2004fb8, ...}, ...)
        github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:692 +0x148
github.com/ledgerwatch/erigon/consensus/parlia.(*Parlia).Finalize(0x0?, 0x0?, 0xc007030480?, 0xc000243b80?, {0xc0e5db1500?, 0xc00d202a00?, 0x454710?}, {0x2d6acc8, 0x0, 0x0}, ...)
        github.com/ledgerwatch/erigon/consensus/parlia/parlia.go:679 +0x66
github.com/ledgerwatch/erigon/core.ExecuteBlockEphemerallyForBSC(0xc0001c4b00, 0xc0e7995140, 0x8?, {0x200d6b0?, 0xc00d202a00}, 0xc0e78f2700, {0x2001c20?, 0xc007030460}, {0x2007750, 0xc0e78fd260}, ...)
        github.com/ledgerwatch/erigon/core/blockchain.go:165 +0x866
github.com/ledgerwatch/erigon/eth/stagedsync.executeBlock(_, {_, _}, {_, _}, {{0x2007610, 0xc00027b3f0}, 0x10000000, {0x1, {0x2002aa0, ...}, ...}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_execute.go:167 +0x43e
github.com/ledgerwatch/erigon/eth/stagedsync.SpawnExecuteBlocksStage(_, {_, _}, {_, _}, _, {_, _}, {{0x2007610, 0xc00027b3f0}, ...}, ...)
        github.com/ledgerwatch/erigon/eth/stagedsync/stage_execute.go:436 +0xedf
github.com/ledgerwatch/erigon/eth/stagedsync.DefaultStages.func16(0xb0?, 0xa0?, 0x1981109?, {0x1fedbe0?, 0xc00a80a0b0?}, {0x0?, 0x0?})
        github.com/ledgerwatch/erigon/eth/stagedsync/default_stages.go:85 +0x90
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).runStage(0xc00a80a0b0, 0xc00d0c4a00, {0x2007610?, 0xc00027b3f0}, {0x0?, 0x0}, 0x50?, 0x53?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:352 +0x150
github.com/ledgerwatch/erigon/eth/stagedsync.(*Sync).Run(0xc00a80a0b0, {0x2007610?, 0xc00027b3f0}, {0x0, 0x0}, 0x0?)
        github.com/ledgerwatch/erigon/eth/stagedsync/sync.go:255 +0x265
github.com/ledgerwatch/erigon/turbo/stages.StageLoopStep({0x1ffea88, 0xc000a4af40}, {0x2007610?, 0xc00027b3f0?}, 0xc00a80a0b0, 0x0, 0xc000a5af80, 0x1, 0xc014df4e60, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:163 +0x445
github.com/ledgerwatch/erigon/turbo/stages.StageLoop({0x1ffea88, 0xc000a4af40}, {0x2007610?, 0xc00027b3f0}, 0x19be385?, 0x27?, 0xa72f00?, 0xc000a2a4e0?, 0xc0092e57b8?, 0x0)
        github.com/ledgerwatch/erigon/turbo/stages/stageloop.go:84 +0x145
created by github.com/ledgerwatch/erigon/eth.(*Ethereum).Start
        github.com/ledgerwatch/erigon/eth/backend.go:883 +0x1e5

goroutine 5447 [syscall]:
os/signal.signal_recv()
        runtime/sigqueue.go:151 +0x2f
os/signal.loop()
        os/signal/signal_unix.go:23 +0x19
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x2a

goroutine 162683 [chan receive]:
github.com/ledgerwatch/erigon/eth.(*Ethereum).Stop(0xc0001fcd80)
        github.com/ledgerwatch/erigon/eth/backend.go:911 +0x189
github.com/ledgerwatch/erigon/node.(*Node).stopServices(0xc007a1b620?, {0xc015324870, 0x1, 0x80aea0?})
        github.com/ledgerwatch/erigon/node/node.go:219 +0xb3
github.com/ledgerwatch/erigon/node.(*Node).Close(0xc000a4eb00)
        github.com/ledgerwatch/erigon/node/node.go:162 +0x18b
created by github.com/ledgerwatch/erigon/internal/debug.ListenSignals
        github.com/ledgerwatch/erigon/internal/debug/signal.go:29 +0x26d
root@ip-172-31-63-1:/home/ubuntu#
```

**Comment by allada** [comment]
Yes, I recently also saw this and have a fix along the way. It will fix itself with enough time and 50 gigs of ram. The reason is because parlor protocol that BSC uses needs some index data that is stored in a different file. This file is not downloaded with the current script so it needs to traverse every block. You can either wait for the new script or download it manually. I don't have the name on hand, but it is in the same bucket and folder as the `mdbx.dat` file on S3.

**Comment by ArielTM** [comment]
Worked like a charm. Fixed at https://github.com/allada/bsc-archive-snapshot/pull/30
